### ISSUE TITLE
postcss-import-ext-glob 2.0.0 not working

### ISSUE THREAD

**Issue by alkorlos** [dimitrinicolas/postcss-import-ext-glob#2]
After update postcss-import-ext-glob from 1.1.0 to 2.0.0 plugin broken. Error: 
postcss-import-ext-glob: PATHTOFILE:7:1: No file found for @import-glob "components/**/*.pcss"
The error appears when updating postcss-import-ext-glob, no other changes.

Environment:
node 14
windows 10
Complete code https://github.com/alkorlos/bundler

**Comment by dimitrinicolas** [comment]
Hi! 😄

Thank you for your feedback, I've just published a fix on version `2.0.1`.
